/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/bundles/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search for bundles */
        get: {
            parameters: {
                query?: {
                    /** @description Search query */
                    q?: string;
                    /** @description Filter by server type */
                    type?: string;
                    sort?: "downloads" | "recent" | "name";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            bundles: {
                                name: string;
                                display_name?: string | null;
                                description?: string | null;
                                author?: {
                                    name: string;
                                } | null;
                                latest_version: string;
                                icon?: string | null;
                                server_type?: string | null;
                                tools?: {
                                    name: string;
                                    description?: string;
                                }[];
                                downloads: number;
                                /** Format: date-time */
                                published_at: string;
                                verified: boolean;
                                provenance?: {
                                    schema_version: string;
                                    provider: string;
                                    repository: string;
                                    sha: string;
                                } | null;
                            }[];
                            total: number;
                            pagination: {
                                limit: number;
                                offset: number;
                                has_more: boolean;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/@{scope}/{package}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get detailed bundle information */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    package: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            display_name?: string | null;
                            description?: string | null;
                            author?: {
                                name: string;
                            } | null;
                            latest_version: string;
                            icon?: string | null;
                            server_type?: string | null;
                            tools?: {
                                name: string;
                                description?: string;
                            }[];
                            downloads: number;
                            /** Format: date-time */
                            published_at: string;
                            verified: boolean;
                            homepage?: string | null;
                            license?: string | null;
                            github?: {
                                repo: string;
                                stars?: number | null;
                                forks?: number | null;
                                watchers?: number | null;
                            } | null;
                            provenance?: {
                                schema_version: string;
                                provider: string;
                                repository: string;
                                sha: string;
                            } | null;
                            versions: {
                                version: string;
                                /** Format: date-time */
                                published_at: string;
                                downloads: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/@{scope}/{package}/index.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get multi-platform distribution index for a bundle (MCPB Index spec) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    package: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            index_version: string;
                            mimeType: string;
                            name: string;
                            version: string;
                            description?: string | null;
                            bundles: {
                                mimeType: string;
                                digest: string;
                                size: number;
                                platform: {
                                    /** @description Operating system (darwin, linux, win32, any) */
                                    os: string;
                                    /** @description Architecture (x64, arm64, any) */
                                    arch: string;
                                };
                                urls: string[];
                            }[];
                            annotations?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/@{scope}/{package}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all versions of a bundle */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    package: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            latest: string;
                            versions: {
                                version: string;
                                artifacts_count: number;
                                platforms: {
                                    /** @description Operating system (darwin, linux, win32, any) */
                                    os: string;
                                    /** @description Architecture (x64, arm64, any) */
                                    arch: string;
                                }[];
                                /** Format: date-time */
                                published_at: string;
                                downloads: number;
                                publish_method?: string | null;
                                provenance?: {
                                    schema_version: string;
                                    provider: string;
                                    repository: string;
                                    sha: string;
                                } | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/@{scope}/{package}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get information about a specific version */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    package: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            version: string;
                            /** Format: date-time */
                            published_at: string;
                            downloads: number;
                            artifacts: {
                                platform: {
                                    /** @description Operating system (darwin, linux, win32, any) */
                                    os: string;
                                    /** @description Architecture (x64, arm64, any) */
                                    arch: string;
                                };
                                digest: string;
                                size: number;
                                download_url: string;
                                source_url?: string;
                            }[];
                            manifest?: {
                                [key: string]: unknown;
                            };
                            release?: {
                                tag?: string;
                                url?: string;
                            } | null;
                            publish_method?: string | null;
                            provenance?: {
                                [key: string]: unknown;
                            } | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/@{scope}/{package}/versions/{version}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download a specific version of a bundle */
        get: {
            parameters: {
                query?: {
                    /** @description Target OS (darwin, linux, win32, any) */
                    os?: string;
                    /** @description Target arch (x64, arm64, any) */
                    arch?: string;
                };
                header?: never;
                path: {
                    scope: string;
                    package: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            url: string;
                            bundle: {
                                name: string;
                                version: string;
                                platform: {
                                    /** @description Operating system (darwin, linux, win32, any) */
                                    os: string;
                                    /** @description Architecture (x64, arm64, any) */
                                    arch: string;
                                };
                                sha256: string;
                                size: number;
                            };
                            /** Format: date-time */
                            expires_at: string;
                        };
                    };
                };
                /** @description Redirect to download URL */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/announce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Announce a new bundle version from a GitHub release (OIDC only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Package name (@scope/name) */
                        name: string;
                        /** @description Semantic version */
                        version: string;
                        /** @description Bundle manifest */
                        manifest: Record<string, never>;
                        /** @description GitHub release tag (e.g., v0.1.0) */
                        release_tag: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            bundle: {
                                name: string;
                                version: string;
                                artifacts_count: number;
                            };
                            release: {
                                tag: string;
                                url: string;
                            };
                            artifacts: {
                                platform: {
                                    /** @description Operating system (darwin, linux, win32, any) */
                                    os: string;
                                    /** @description Architecture (x64, arm64, any) */
                                    arch: string;
                                };
                                digest: string;
                                size: number;
                                url: string;
                                source_url: string;
                            }[];
                            provenance: {
                                schema_version: string;
                                provider: string;
                                repository: string;
                                sha: string;
                            } | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Health check endpoint */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
